// <auto-generated />
using LorcanaCardCollector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LorcanaCardCollector.Migrations
{
    [DbContext(typeof(CardsContext))]
    [Migration("20250925153839_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LorcanaCardCollector.Models.Cards", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GemColor")
                        .HasColumnType("int");

                    b.Property<bool>("InADeck")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Collection");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CardName = "Rhino - Motivational Speaker",
                            GemColor = 10,
                            InADeck = true,
                            Quantity = 1,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            ID = 2,
                            CardName = "Perdita - Playful Mother",
                            GemColor = 9,
                            InADeck = false,
                            Quantity = 1,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            ID = 3,
                            CardName = "King Stefan - New Father",
                            GemColor = 0,
                            InADeck = true,
                            Quantity = 2,
                            SetName = "Archazilia's Island"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
