// <auto-generated />
using LorcanaCardCollector.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LorcanaCardCollector.Migrations
{
    [DbContext(typeof(CardsContext))]
    partial class CardsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LorcanaCardCollector.Models.Cards", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GemColor")
                        .HasColumnType("int");

                    b.Property<bool>("InADeck")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Collection");

                    b.HasData(
                        new
                        {
                            ID = "ARI-001",
                            CardName = "Rhino - Motivational Speaker",
                            GemColor = 10,
                            InADeck = true,
                            Quantity = 1,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            ID = "ARI-002",
                            CardName = "Perdita - Playful Mother",
                            GemColor = 9,
                            InADeck = false,
                            Quantity = 1,
                            SetName = "Archazia's Island"
                        },
                        new
                        {
                            ID = "AIR-003",
                            CardName = "King Stefan - New Father",
                            GemColor = 0,
                            InADeck = true,
                            Quantity = 2,
                            SetName = "Archazilia's Island"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
